### PR TITLE
refactor(export): Remove export as JSON parameter - Issue #139

### LINKED ISSUE #139: Running export command with 'json' option outputs help information
Command taken from the readme: `node lib/run.js export --projectKey <project_key> --clientId <client_id> --clientSecret <client_secret> -j out.json`

Running this results in command usage output being shown, from `--help`.

The culprit seems to be the json option.

### PR DESCRIPTION
**Pull request by junajan**
Fixes #139

### CODE REVIEW

**Comment by junajan** [comment]
Currently, the JSON output does not work so it is not a breaking change I suppose.

**Comment by Siilwyn** [comment]
Please remember to delete the branch in future PRs. 👉  delete right after clicking merge

**Comment by junajan** [comment]
Ahh.. thx @Siilwyn :sunny:

**Comment by hisabimbola** [comment]
Several PRs have been merged, so please draft a release note and we do a release.

**Pull request merged**
