### PR TITLE
Add price validity support to product export/import - Issue #150

### PR DESCRIPTION
**Pull request by junajan**
This PR resolves issue #150

### CODE REVIEW

**Comment by hisabimbola** [comment]
@junajan Can you add the new implementation to the readme

**Comment by junajan** [comment]
@hisabimbola - updated here 77ed1aa

**Comment by hisabimbola** [comment]
Cool, please squash and draft a release note [here](https://github.com/sphereio/sphere-node-product-csv-sync/releases)

**Comment by junajan** [comment]
@hisabimbola - draft added here: https://github.com/sphereio/sphere-node-product-csv-sync/releases/edit/untagged-987893c6fcc6fa6d167d

**Pull request merged**
