### PR TITLE
Categories by external

### PR DESCRIPTION
**Pull request by mmoelli**
@hajoeichler @emmenko Please check.

### CODE REVIEW

**Comment by mmoelli** [comment]
https://github.com/sphereio/sphere-node-product-csv-sync/issues/52

**Comment by hajoeichler** [comment]
thx @mmoelli.
I would not introduce a new column as it has 2 drawbacks:
- the current implementation already has 2 different ways to resolve categories and they use only one header
- having two different columns for the same property make it unclear what to do when both headers are provided.

Let's have the resolve order like this:
- externalId
- named path
- name

**Comment by mmoelli** [comment]
how do I distinguish between {{name}} and {{externalId}} when using the same header?

**Comment by mmoelli** [comment]
@emmenko as @hajoeichler is out of order now, maybe you can help.

**Comment by emmenko** [comment]
@mmoelli I'm a bit out of context here. Also I'm not really familiar with the csv stuff...

**Comment by mmoelli** [comment]
Thanks anyway @emmenko 

@hajoeichler would it be an option to use a cli parameter to define the category mapping e.g. `--categoryBy name` (default) or `--categoryBy externalId`

**Comment by butenkor** [comment]
Why can't you check by convention if column header for category is "name", "externalId" or "path"?

**Comment by mmoelli** [comment]
@butenkor how would this look like in the CSV?

**Comment by butenkor** [comment]
instead of header ```categories``` you may define then:

```categories.name``` - fetch by category name. 
Example value: "My Category"

```categories.slug``` - fetch by category slug (could be also ```categories.slug.de``` ). 
Example value: "my-category"

```categories.path``` -  fetch by category path (which will map internally by name). 
Example value: "Root -> My Category"

```categories.externalId``` - fetch by category externalId. 
Example value: "12345"

```categories``` - for backwards compatibility will map to  ```categories.name```. 
Example value: "My Category"

**Comment by mmoelli** [comment]
@butenkor the question from @hajoeichler remains how to handle than multiple category headers, especially if they are not mapping to the same categories

**Comment by butenkor** [comment]
You wanted to introduce additional column for your solution. My approach uses 1 column only but it does different things depending on column header name so you do not have to handle multiple category headers.

**Pull request merged**
